version: '3.7'
services:

  tof_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: bobbyahines/tof:latest
    container_name: tof_server
    restart: unless-stopped
    networks:
      - frontend
      - backend
    ports:
      - "5000:5000"
    links:
        - tof_db:db
    entrypoint: python3
    command: run.py

  tof_db:
    build:
      context: .
      dockerfile: Dockerfile-db
    image: tof/mysql:5.7
    container_name: tof_db
    restart: unless-stopped
    networks:
      - backend
    expose:
      - "3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=tof
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
# If you'd like to persist the data between restarts, you can uncomment the volumes lines.
#    volumes:
#      - ./db:/var/lib/mysql
