FROM mysql:5.7
LABEL maintainer="Bobby Hines <bobbyahines@gmail.com>"
LABEL image="tof/mysql:5.7"

# Add a database
ENV MYSQL_DATABASE tof
ENV MYSQL_USER user
ENV MYSQL_PASSWORD pass
ENV MYSQL_HOST db

RUN apt-get update -y && apt-get install git nano -y

#Clone in the server source code, and move it to the srv dir.
RUN git clone https://github.com/P1X-in/tanks-of-freedom-server.git
RUN cp ./tanks-of-freedom-server/sql/*.sql /docker-entrypoint-initdb.d/
RUN rm -Rf ./tanks-of-freedom-server/
